### ISSUE TITLE
Fix wording

### ISSUE THREAD

**Issue by nicolae-stroncea** [kelvinfan001/findalicious#99]
**Is your feature request related to a problem? Please describe.**
Wording is very unfriendly for people with no friends. Some of my best friends told me they face this issue and feel sad whenever they have to click "everyone is in the room" and it highlights that only "1 user in this room". Please fix this urgently.

**Describe the solution you'd like**
I ask that you either reword the text or automatically join every room so people have at least another friend there.

**Describe alternatives you've considered**
Having friends

**Additional context**

![image](https://user-images.githubusercontent.com/39338488/99625767-ed06a600-29fe-11eb-846d-903b630329a2.png)

**Comment by kelvinfan001** [comment]
Please try the alternative harder :) 
If the issue persists, feel free to submit a PR to resolve it.

**Comment by nicolae-stroncea** [comment]
I will pass this on to my friends!
